/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __com_qtec_cameracalibration_server_V4L2CamInterface__
#define __com_qtec_cameracalibration_server_V4L2CamInterface__

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT jobject JNICALL Java_com_qtec_cameracalibration_server_V4L2CamInterface_getVideoDevices (JNIEnv *env, jobject);
JNIEXPORT jstring JNICALL Java_com_qtec_cameracalibration_server_V4L2CamInterface_getDriverName (JNIEnv *env, jobject, jstring);
JNIEXPORT jobject JNICALL Java_com_qtec_cameracalibration_server_V4L2CamInterface_getTestGenDevices (JNIEnv *env, jobject);
JNIEXPORT jobject JNICALL Java_com_qtec_cameracalibration_server_V4L2CamInterface_getControlList (JNIEnv *env, jobject, jstring);
JNIEXPORT jint JNICALL Java_com_qtec_cameracalibration_server_V4L2CamInterface_setControl (JNIEnv *env, jobject, jstring, jint, jstring);
JNIEXPORT jint JNICALL Java_com_qtec_cameracalibration_server_V4L2CamInterface_setControlArray (JNIEnv *env, jobject, jstring, jint, jintArray);
JNIEXPORT jobject JNICALL Java_com_qtec_cameracalibration_server_V4L2CamInterface_getControl (JNIEnv *env, jobject, jstring, jint);
JNIEXPORT jstring JNICALL Java_com_qtec_cameracalibration_server_V4L2CamInterface_getControlValue (JNIEnv *env, jobject, jstring, jint);
JNIEXPORT jintArray JNICALL Java_com_qtec_cameracalibration_server_V4L2CamInterface_getExtControlDefValues (JNIEnv *env, jobject, jstring, jint);
JNIEXPORT jint JNICALL Java_com_qtec_cameracalibration_server_V4L2CamInterface_increaseControl (JNIEnv *env, jobject, jstring, jint);
JNIEXPORT jint JNICALL Java_com_qtec_cameracalibration_server_V4L2CamInterface_decreaseControl (JNIEnv *env, jobject, jstring, jint);
JNIEXPORT jdouble JNICALL Java_com_qtec_cameracalibration_server_V4L2CamInterface_setFps (JNIEnv *env, jobject, jstring, jdouble);
JNIEXPORT jdouble JNICALL Java_com_qtec_cameracalibration_server_V4L2CamInterface_getFps (JNIEnv *env, jobject, jstring);
JNIEXPORT jint JNICALL Java_com_qtec_cameracalibration_server_V4L2CamInterface_startGrabber (JNIEnv *env, jclass, jobject);
JNIEXPORT jint JNICALL Java_com_qtec_cameracalibration_server_V4L2CamInterface_stopGrabber (JNIEnv *env, jclass, jobject);
JNIEXPORT jobject JNICALL Java_com_qtec_cameracalibration_server_V4L2CamInterface_getFrame (JNIEnv *env, jclass, jobject, jobject);
JNIEXPORT jobject JNICALL Java_com_qtec_cameracalibration_server_V4L2CamInterface_getRawFrame (JNIEnv *env, jclass, jobject);
JNIEXPORT jbyteArray JNICALL Java_com_qtec_cameracalibration_server_V4L2CamInterface_getBMPFrame (JNIEnv *env, jclass, jobject, jobject);
JNIEXPORT jbyteArray JNICALL Java_com_qtec_cameracalibration_server_V4L2CamInterface_getJPEGFrame (JNIEnv *env, jclass, jobject, jobject);
JNIEXPORT jint JNICALL Java_com_qtec_cameracalibration_server_V4L2CamInterface_setTestGenFrame (JNIEnv *env, jclass, jobject);
JNIEXPORT jbyteArray JNICALL Java_com_qtec_cameracalibration_server_V4L2CamInterface_getJPGPictureFromRawImageJNI (JNIEnv *env, jclass, jobject, jobject);
JNIEXPORT jobject JNICALL Java_com_qtec_cameracalibration_server_V4L2CamInterface_getPPMPictureFromRawImageJNI (JNIEnv *env, jclass, jobject, jobject);
JNIEXPORT jobjectArray JNICALL Java_com_qtec_cameracalibration_server_V4L2CamInterface_getHistogramData (JNIEnv *env, jclass, jobject, jint, jobject, jobject);
JNIEXPORT jobjectArray JNICALL Java_com_qtec_cameracalibration_server_V4L2CamInterface_getHistogramDataFromRawImage (JNIEnv *env, jclass, jobject, jint, jobject, jobject);
JNIEXPORT jobject JNICALL Java_com_qtec_cameracalibration_server_V4L2CamInterface_getFrameData (JNIEnv *env, jclass, jobject, jobject, jobject);
JNIEXPORT jobject JNICALL Java_com_qtec_cameracalibration_server_V4L2CamInterface_getGreyRange (JNIEnv *env, jclass, jobject, jobject);
JNIEXPORT jobject JNICALL Java_com_qtec_cameracalibration_server_V4L2CamInterface_getGreyRangeFromRawImage (JNIEnv *env, jclass, jobject, jobject);
JNIEXPORT jobject JNICALL Java_com_qtec_cameracalibration_server_V4L2CamInterface_getSupportedPixelFormats (JNIEnv *env, jobject, jstring);
JNIEXPORT jint JNICALL Java_com_qtec_cameracalibration_server_V4L2CamInterface_setPixelFormat (JNIEnv *env, jobject, jstring, jobject);
JNIEXPORT jobject JNICALL Java_com_qtec_cameracalibration_server_V4L2CamInterface_getPixelFormat (JNIEnv *env, jobject, jstring);
JNIEXPORT jobject JNICALL Java_com_qtec_cameracalibration_server_V4L2CamInterface_getSupportedFrameSizes (JNIEnv *env, jobject, jstring, jint);
JNIEXPORT jobject JNICALL Java_com_qtec_cameracalibration_server_V4L2CamInterface_getSupportedFrameRates (JNIEnv *env, jobject, jstring, jint, jint, jint);
JNIEXPORT jint JNICALL Java_com_qtec_cameracalibration_server_V4L2CamInterface_setFrameSize (JNIEnv *env, jobject, jstring, jint, jint);
JNIEXPORT jintArray JNICALL Java_com_qtec_cameracalibration_server_V4L2CamInterface_getFrameSize (JNIEnv *env, jobject, jstring);
JNIEXPORT jobject JNICALL Java_com_qtec_cameracalibration_server_V4L2CamInterface_getCropCapabilities (JNIEnv *env, jobject, jstring);
JNIEXPORT jint JNICALL Java_com_qtec_cameracalibration_server_V4L2CamInterface_setCrop (JNIEnv *env, jobject, jstring, jobject);
JNIEXPORT jobject JNICALL Java_com_qtec_cameracalibration_server_V4L2CamInterface_getCrop (JNIEnv *env, jobject, jstring);
JNIEXPORT jobject JNICALL Java_com_qtec_cameracalibration_server_V4L2CamInterface_getMultiSelection (JNIEnv *env, jobject, jstring);
JNIEXPORT jint JNICALL Java_com_qtec_cameracalibration_server_V4L2CamInterface_setMultiSelection (JNIEnv *env, jobject, jstring, jobject);
JNIEXPORT jobject JNICALL Java_com_qtec_cameracalibration_server_V4L2CamInterface_calibSensorGst (JNIEnv *env, jobject, jstring, jstring, jobject);
JNIEXPORT jobject JNICALL Java_com_qtec_cameracalibration_server_V4L2CamInterface_recordImagesGst (JNIEnv *env, jobject, jstring, jint, jstring);

#ifdef __cplusplus
}
#endif

#endif /* __com_qtec_cameracalibration_server_V4L2CamInterface__ */
